### ISSUE TITLE
Moon Tester Tool blocked by PM 29.4.2.1

### ISSUE THREAD

**Issue by PotentialTumbleweed** [JustOff/moon-tester-tool#14] opened 2021-11-16 00:11 UTC
Created some new profiles with Pale Moon on Windows 10. Discovered that I could not install Moon Tester Tool. In my older profiles, I had MTT installed already, and they have not been disturbed.

**Comment by JustOff** [comment] 2021-11-16 08:49
Duplicate of #10.

**Closed as completed by JustOff** 2021-11-16 08:49 UTC
Labels: duplicate
